# run with:
#     gh workflow run CI --ref "$(git rev-parse --abbrev-ref HEAD)"
# otherwise it just happens automatically on push or pr

name: CI
env:
  AC_GITHUB_ACCESS_TOKEN: ${{ secrets.AC_GITHUB_ACCESS_TOKEN }}
  BADGE_BUCKET: ${{ secrets.BADGE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SLACK_ALERT_CHANNEL_WEBHOOK: ${{ secrets.SLACK_ALERT_CHANNEL_WEBHOOK }}
  SLACK_CHANNEL_WEBHOOK:  ${{ secrets.SLACK_CHANNEL_WEBHOOK }}

on:
  push:
  workflow_dispatch:
  schedule:
    # 1pm est = '0 17 * * *'
    - cron:  '0 17 * * *'

jobs:
  env-check-prod:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/solutions-team-280017/swiss-alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: env-check-prod
        run: ./github_smoke_test.sh "env$GITHUB_RUN_ID" "env-check" "default.prod"
